### ISSUE TITLE
v3.0.1-rc3: IP not found and agent_timeout not being used

### ISSUE THREAD

**Issue by arty-hlr** [Telmate/terraform-provider-proxmox#1106]
Contrary to the PR https://github.com/Telmate/terraform-provider-proxmox/pull/1016 and to what the documentation https://registry.terraform.io/providers/telmate/proxmox/3.0.1-rc3/docs/resources/vm_qemu says, `agent_timeout` is not being used, which results in VMs being created and then the following error:
![image](https://github.com/user-attachments/assets/50f36353-1912-4194-8d45-89f13300ece2)

I do use `agent_timeout` in the module:
![image](https://github.com/user-attachments/assets/70813281-2770-45fe-92df-40ef23a7a626)

but it's not being shown in the plan output:
![image](https://github.com/user-attachments/assets/d96ba236-9cb3-41d5-acad-755228cf839a)

The only difference with previous templates I tried to clone is that there is now SSH installed. I am not sure why it cannot find the IP address as it shows it in the GUI. I would expect `agent_timeout` to help, as the error suggests, but it does not do anything unfortunately. It also *sometimes* work on one VM or the other, pretty randomly as it seems, so doing multiple `terraform apply` helps, kinda.

Here is the full output with TF_VAR_LOG=DEBUG:
![image](https://github.com/user-attachments/assets/dddc22b9-000e-4758-9cd3-51a25bb01bb9)

## To reproduce:
- create a windows template with SSH server installed and clone it (linked clone) with terraform
- create a VM from a template with terraform and use `agent_timeout`

**Comment by GMZwinge** [comment]
Test without Cloud-init (`os_type = "centos"`):
- `3.0.1-rc3` provides an IP address:
```
2024-10-02T10:56:03.512-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc3.exe: 2024/10/02 10:56:03 [DEBUG] VM is running, checking the IP: timestamp=2024-10-02T10:56:03.512-0400
2024-10-02T10:56:03.512-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc3.exe: 2024/10/02 10:56:03 [INFO][initConnInfo] trying to get vm ip address for provisioner: timestamp=2024-10-02T10:56:03.512-0400
2024-10-02T10:56:03.512-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc3.exe: 2024/10/02 10:56:03 [DEBUG][initConnInfo] retrying for at most  20m0s minutes before giving up: timestamp=2024-10-02T10:56:03.512-0400
2024-10-02T10:56:03.512-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc3.exe: 2024/10/02 10:56:03 [DEBUG][initConnInfo] retries will end at 2024-10-02 11:16:03.5122731 -0400 EDT m=+1224.259660501: timestamp=2024-10-02T10:56:03.512-0400
2024-10-02T10:56:06.525-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc3.exe: 2024/10/02 10:56:06 [INFO][getPrimaryIP] check ip result error 500 QEMU guest agent is not running: timestamp=2024-10-02T10:56:06.524-0400
2024-10-02T10:56:14.566-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc3.exe: 2024/10/02 10:56:14 [INFO][getPrimaryIP] check ip result error 500 QEMU guest agent is not running: timestamp=2024-10-02T10:56:14.565-0400
2024-10-02T10:56:19.712-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc3.exe: 2024/10/02 10:56:19 [INFO][getPrimaryIP] QEMU Agent interfaces found: [{00:00:00:00:00:00 [127.0.0.1 ::1] lo <nil>} {<MacAddress> [<Ipv6Addresses>] ens18 <nil>}]: timestamp=2024-10-02T10:56:19.712-0400
2024-10-02T10:56:24.922-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc3.exe: 2024/10/02 10:56:24 [INFO][getPrimaryIP] QEMU Agent interfaces found: [{00:00:00:00:00:00 [127.0.0.1 ::1] lo <nil>} {<MacAddress> [<Ipv4Address> <Ipv6Addresses>] ens18 <nil>}]: timestamp=2024-10-02T10:56:24.922-0400
2024-10-02T10:56:24.922-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc3.exe: 2024/10/02 10:56:24 [DEBUG][initConnInfo] this is the vm configuration: <Ipv4Address> 22: timestamp=2024-10-02T10:56:24.922-0400
```
- `3.0.1-rc4` doesn't provide an IP address:
```
2024-10-02T10:53:14.311-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc4.exe: 2024/10/02 10:53:14 [DEBUG] VM is running, checking the IP: timestamp=2024-10-02T10:53:14.311-0400
2024-10-02T10:53:14.311-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc4.exe: 2024/10/02 10:53:14 [INFO][initConnInfo] trying to get vm ip address for provisioner: timestamp=2024-10-02T10:53:14.311-0400
2024-10-02T10:53:14.311-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc4.exe: 2024/10/02 10:53:14 [DEBUG][initConnInfo] retrying for at most  20m0s minutes before giving up: timestamp=2024-10-02T10:53:14.311-0400
2024-10-02T10:53:14.311-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc4.exe: 2024/10/02 10:53:14 [DEBUG][initConnInfo] retries will end at 2024-10-02 11:13:14.3111935 -0400 EDT m=+1221.822484201: timestamp=2024-10-02T10:53:14.311-0400
2024-10-02T10:53:14.311-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc4.exe: 2024/10/02 10:53:14 [INFO][getPrimaryIP] vm has a cloud-init configuration: timestamp=2024-10-02T10:53:14.311-0400
2024-10-02T10:53:14.311-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc4.exe: 2024/10/02 10:53:14 [DEBUG][initConnInfo] this is the vm configuration:  22: timestamp=2024-10-02T10:53:14.311-0400
```
Also, it displays those warning: `Warning: Cloud-init is enabled but no IP config is set` and `Cloud-init is enabled in your configuration but no static IP address is set, nor is the DHCP option enabled`. Was able to get rid of those warning with `define_connection_info = false`, but it still doesn't provide an IP address:
```
2024-10-02T11:09:14.978-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc4.exe: 2024/10/02 11:09:14 [DEBUG] VM is running, checking the IP: timestamp=2024-10-02T11:09:14.978-0400
2024-10-02T11:09:14.978-0400 [INFO]  provider.terraform-provider-proxmox_v3.0.1-rc4.exe: 2024/10/02 11:09:14 [INFO][initConnInfo] define_connection_info is false, no further action: timestamp=2024-10-02T11:09:14.978-0400
```
Not sure if that's the correct way to NOT use Cloud-init though.

**Comment by Tinyblargon** [comment]
Found the commit that most likely broke it.
Ironically it separated the logic so it would be easier to test.

https://github.com/Telmate/terraform-provider-proxmox/commit/18095e5a3ee23b44029b22693b687eb6e9dac6ad#diff-104365919f693375882979581d9f36f5266991eef361948e56c220931fe886ddL1916

**Comment by Tinyblargon** [comment]
@GMZwinge could you check if #1120 fixes your issue?

**Comment by Tinyblargon** [comment]
@arty-hlr 

`agent_timeout` is being used, it could be that `endTime` on L1970 is shorter, but by default this is 20 minutes.

https://github.com/Telmate/terraform-provider-proxmox/blob/a9a0bad342b4bb73b662694142bb78015e04aa38/proxmox/resource_vm_qemu.go#L1970-L1994


However, it the log your showed does show the information in it's raw form.
I think we are parsing the MAC address wrong and therefore we can't match it with an interface returned by the `guest-agent`.
https://github.com/Telmate/terraform-provider-proxmox/blob/a9a0bad342b4bb73b662694142bb78015e04aa38/proxmox/resource_vm_qemu.go#L1965-L1968

Upstream I'm working on re-implementingthe network interfaces to get rid of this regex parsing of the MAC address on L1966.

**Comment by Tinyblargon** [comment]
@arty-hlr can you check if #1120 fixes your issue?

**Comment by arty-hlr** [comment]
@Tinyblargon How do I tell terraform/opentofu to use your branch? I only see `source` and `version` in the terraform provider config. Should I compile it, and copy the executable to the plugin directory like [here](https://github.com/Tinyblargon/terraform-provider-proxmox/blob/%231106/docs/guides/installation.md#copy-executables-to-plugin-directory-terraform-013)?

**Comment by arty-hlr** [comment]
about `agent_timeout`: I did try to change its value, but it didn't make any difference, so I assumed it wasn't used at all as it wasn't in the logs.

**Comment by Tinyblargon** [comment]
@arty-hlr when you compile the branch, the compiled binary has to be renamed to `linux_amd64`, then you can put at `.terraform/providers/terraform.local/local/proxmox/1.0.0/linux_amd64` inside your terraform project [developer.md](https://github.com/Tinyblargon/terraform-provider-proxmox/blob/f6961324ec3d0901a3e8fc5bbee789eb258f0a33/docs/guides/developer.md) has more information about this.

**Comment by arty-hlr** [comment]
Hi @Tinyblargon, that didn't work, I had to change the .terraformrc to add a filesystem mirror, unfortunately that's not mentioned anywhere in the docs.

I just ran a test with your branch and unfortunately it still doesn't work, here's the relevant part of the output:

![grafik](https://github.com/user-attachments/assets/bd5c591d-d423-4812-a6d1-fe8057b33960)

It seems that looping over `terraform apply` (which worked before) doesn't anymore either.

![grafik](https://github.com/user-attachments/assets/195e3797-7a63-491b-922c-c24f1e227a43)

**Comment by Tinyblargon** [comment]
@arty-hlr 

Checking if i have the correct situation.

- `os_type` == `"cloud-init"`
- a cloud-init disk is configured
- `skip_ipv4` == true
- `skip_ipv6` == false


The error is telling me that `ipconfig0` is not configured.

**Comment by arty-hlr** [comment]
@Tinyblargon The same happens with `os_type` as `cloud-init` or `cloud-init` not set at all, the above screenshots from the run were with `cloud-init` not set at all. There is no cloud-init disk configured, the VMs are just cloned from the template and get a dynamic IP address from the DHCP server, so I don't use `ipconfig0` as there's no actual cloud-init.

I'm actually not sure why it says `Cloud-init` is enabled because it is not in the terraform config and the templates don't have a cloud-init drive.

![grafik](https://github.com/user-attachments/assets/63fbccb0-bfe8-44d0-90d4-e6d993e1dc10)

**Comment by Tinyblargon** [comment]
@arty-hlr made some changes and tested locally.
It now works as expected and reliably gets an IP address.
Did 2 test, one VM with cloud-init, and one VM without cloud-init with pre-configured DHCP.

**Comment by Tinyblargon** [comment]
@GMZwinge @arty-hlr could you test if the latest release solves your issue?

**Comment by arty-hlr** [comment]
Sorry for the late answer, will do today and let you know

**Comment by arty-hlr** [comment]
@Tinyblargon Unfortunately same problem with the latest release (rc6) 😢  the provider couldn't get the IP of one of the VMs even though it was up and showed an IP on proxmox.

![image](https://github.com/user-attachments/assets/4138e2a9-4e39-4efb-9124-effe9a3f9cbd)

Here the next test run, I was checking the VMs in proxmox as they were created and all 5 got an IP and displayed it, somehow the provider couldn't find the IP for 3 of them:

![image](https://github.com/user-attachments/assets/593dc434-1b2c-432c-83ed-a8e29c1799e5)

**Comment by Tinyblargon** [comment]
@arty-hlr could you set the `agent_timeout` really high and see if it has different results?
Does the vm have a `net0` network interface? I believe it only checks for that one. The GUI does display the ip of the lowest `net` adapter.

**Comment by Tinyblargon** [comment]
@arty-hlr Could you check if the debug logs show the following errors? It will show the raw data of the `qemu-guest-agent`.

https://github.com/Telmate/terraform-provider-proxmox/blame/7e667094714d35f66c8d45ef08400895e1ad6804/proxmox/resource_vm_qemu.go#L1679-L1680

**Comment by arty-hlr** [comment]
@Tinyblargon So, I think we're getting closer. This is how it looks like when the IP is found:
![image](https://github.com/user-attachments/assets/c131d5da-ae87-4c81-a59b-7aaa9ed166e2)

and this is when the IP is not found:
![image](https://github.com/user-attachments/assets/9f94e825-9987-4478-a162-1f348c20494b)

Here's the whole log file: https://gist.github.com/arty-hlr/6c25344a04e9fcfdebcbb02c5a1830f5

For me it looks like the qemu guest agent returns a temporary IP address (169.254.XXX.XXX) which is then not parsed correctly somehow. I'd suggest maybe waiting until an actual private IP is returned by the qemu guest agent?

**Comment by Tinyblargon** [comment]
@arty-hlr `192.254.xxx.xxx` is used by windows for local addresses when it didn't get dhcp yet?

**Comment by arty-hlr** [comment]
@Tinyblargon 169.254.xxx.xxx, yes. When I look at the VM in proxmox in real time, I usually see a second or so with that IP before the actual IP is given by the DHCP server. It could be a "slow" race condition between when the provider checks and when the IP is given? Then maybe checking if the IP is in 10.0.0.0/8, 172.16.0.0/12, or 192.168.0.0/16 could be worth doing? But that implies it's supposed to be a private IP though. Then maybe just ignoring 169.254.xxx.xxx would be better? Just throwing ideas

**Comment by Tinyblargon** [comment]
@arty-hlr After doing some more research these are `Link-Local` addresses and should be ignored.
https://en.wikipedia.org/wiki/Link-local_address

**Comment by arty-hlr** [comment]
@Tinyblargon Yes exactly. Do you mean they should already be ignored, or it should be fixed so that they are? From what I can see it is reported by `getPrimaryIP` but not printed in `initConnInfo`.

**Comment by Tinyblargon** [comment]
@arty-hlr it should be fixed so they are ignored.

**Comment by dangmai** [comment]
I'm still seeing this behavior with `3.0.1-rc9`, i.e. `agent_timeout` doesn't seem to be used, here's a log of the plugin when this happens (I was just running `terraform plan` here):

```
2025/05/26 18:15:14 [DEBUG] VM status: running
2025/05/26 18:15:14 [DEBUG] VM is running, checking the IP
2025/05/26 18:15:14 [INFO][initConnInfo] trying to get vm ip address for provisioner
Mon, 26 May 2025 18:15:14 -0700 INF github.com/Telmate/terraform-provider-proxmox/v2/proxmox/resource_vm_qemu.go:1540 > trying to get vm ip address for provisioner loggerName=initConnInfo vmid=106
2025/05/26 18:15:14 [INFO][getPrimaryIP] vm has a cloud-init configuration
Mon, 26 May 2025 18:15:14 -0700 DBG github.com/Telmate/terraform-provider-proxmox/v2/proxmox/resource_vm_qemu.go:1601 >  vm has a cloud-init configuration loggerName=getPrimaryIP vmid=106
2025/05/26 18:15:14 [DEBUG][initConnInfo] retrying for at most  0s before giving up
2025/05/26 18:15:14 [DEBUG][initConnInfo] retries will end at 2025-05-26 18:15:14.626008915 -0700 PDT m=+0.267268796
Mon, 26 May 2025 18:15:14 -0700 DBG github.com/Telmate/terraform-provider-proxmox/v2/proxmox/resource_vm_qemu.go:1642 > retrying for at most  0s before giving up loggerName=getPrimaryIP vmid=106
Mon, 26 May 2025 18:15:14 -0700 DBG github.com/Telmate/terraform-provider-proxmox/v2/proxmox/resource_vm_qemu.go:1643 > retries will end at 2025-05-26 18:15:14.626008915 -0700 PDT m=+0.267268796 loggerName=getPrimaryIP vmid=106
2025/05/26 18:15:14 [DEBUG][initConnInfo] this is the vm configuration:  22
```

I've tried setting `agent_timeout` to 90, and remove it completely, but it doesn't seem to be in effect at all (as you can see in the log - it's retrying for at most 0s), and the plugin can't get the IP of the running VM.
