### ISSUE TITLE
terraform apply results in Error: 400 Parameter verification failed.

### ISSUE THREAD

**Issue by TechBrain64** [Telmate/terraform-provider-proxmox#1201]
Terraform: 1.10
Telmate: 2.9.14 and 3.0.1-rc6
Proxmox: 8.3.1

![proxmox_vm_qemu_Error_400](https://github.com/user-attachments/assets/1a717a6d-8e90-4b67-a726-c494117d041d)

I've spent to past two days trying to overcome this issue. "terraform plan" validates successfully, but "terraform apply" fails ever time regards of either version used. I read somewhere here users were experiencing the error, but the VM was still created; that's not my experience.

**Comment by Tinyblargon** [comment]
@TechBrain64 this is the default error PVE gives when something is wrong with some setting in the request. The only real way to debug this is by starting with a minimal config and slowly introducing more settings until it breaks again.

The validation for terraform plan has been meticulously cobbled together by experimening and reading the source code of PVE.

**Comment by TechBrain64** [comment]
@Tinyblargon, I've done as you've suggested and still same error. Here is my minimum configuration:

![proxmox_vm_qemu_Configuration](https://github.com/user-attachments/assets/ac1b3eb6-6a58-4dac-b803-05d3a33287c2)

I am attempting to clone an existing Windows 11 VM template to a new terraform VM. The two variables are defined in a .tfvars with host IP address and template name.

**Comment by Tinyblargon** [comment]
@TechBrain64 If this minimal example already gives issues, then it's probably a default value that's causing this.

Could you create a new vm with minimal configuration and attempt to clone it with terraform? It could be that it's trying to preserve some setting of the vm you are cloning, while the syntax for that setting has changed.

**Comment by maksimsamt** [comment]
> The two variables are defined in a .tfvars with host IP address and template name.

**Comment by Tinyblargon** [comment]
@TechBrain64 

I tried the following but om my it does work:
```hcl
resource "proxmox_vm_qemu" "windows_11_client" {
    vmid = 901
    name = "win11-vm-01"
    target_node = "pve-latest"
    clone = "Debian-12"
}
```

Could you go query for your template `/api2/json/nodes/{node}/qemu/{vmid}/config` and post the results here?

**Comment by TechBrain64** [comment]
@Tinyblargon 

`
    "data": {
        "template": 1,
        "smbios1": "uuid=1ddfb442-ae3e-4d08-b435-b17665962694",
        "net0": "virtio=BC:24:11:BF:4D:DE,bridge=vmbr0,firewall=1",
        "vmgenid": "11e8664a-4b72-4813-bd4d-8454113a60d3",
        "bios": "ovmf",
        "boot": "order=sata0;net0",
        "balloon": 0,
        "vga": "std",
        "agent": "1",
        "name": "w11-24h2-uefi-Eval",
        "digest": "e201dd63c8ed64a7086e9f50f4a9d0745a02601d",
        "meta": "creation-qemu=9.0.2,ctime=1733659880",
        "efidisk0": "NAS-ISCSI-VOL-B:vm-907-disk-0,efitype=4m,size=4M",
        "cpu": "x86-64-v2-AES",
        "numa": 0,
        "tags": "templates",
        "machine": "pc-q35-9.0",
        "ostype": "win11",
        "memory": "4096",
        "cores": 2,
        "sockets": 1,
        "sata0": "NAS-ISCSI-VOL-B:vm-907-disk-1,discard=on,size=75G,ssd=1",
        "tpmstate0": "NAS-ISCSI-VOL-B:vm-907-disk-2,size=4M,version=v2.0",
        "scsihw": "virtio-scsi-single"
    }
}`

**Comment by TechBrain64** [comment]
@Tinyblargon do you have any feedback on my previous response?

**Comment by spettinichi** [comment]
I am using Terraform 1.10.2, in case that helps. What are you on @TechBrain64 ?
```
 terraform -v
Terraform v1.10.2
on darwin_arm64
```

**Comment by TechBrain64** [comment]
Terraform v1.10.1
on linux_amd64

**Comment by TechBrain64** [comment]
@Tinyblargon 

I've been trying any and everything I can find to resolve this issue and still no good.

![terraform_plan-block_syntx_error](https://github.com/user-attachments/assets/f9342e0f-f080-4cdd-899b-89f38dd1f743)

Also, I cannot overcome the syntax error on the "network" block. I'm using Hashicorp/terraform extention v2.43.1 in VSCode v1.96.1.

**Comment by spettinichi** [comment]
that could just be an issue with the plugin, but could you share the whole file to check? the error printing seems unrelated to the syntax validation in vscode

**Comment by Tinyblargon** [comment]
@TechBrain64 Sorry, I haven't had time to look at it yet.

With the `network`, it's missing the `id` of the adapter.

**Comment by TechBrain64** [comment]
@Tinyblargon 

Once I add the ID the "terraform plan" flags it as invalid argument.

**Comment by TechBrain64** [comment]
![terraform_configuration](https://github.com/user-attachments/assets/1592178e-587a-4036-8800-61662e9447dc)

**Comment by Tinyblargon** [comment]
@TechBrain64 for the `disk`, `slot` should be something like `scsi0`

**Comment by TechBrain64** [comment]
@Tinyblargon 

I've made that change, but still fails because of network "id = 0".

**Comment by TechBrain64** [comment]
@spettinichi 

No, I've reverted back to 2.9.14. Making sure I'm not dealing with a RC bug.

**Comment by spettinichi** [comment]
ah then yes id is not present in 2.9.14, I believe it was added in 3.0.1-rc5

**Comment by TechBrain64** [comment]
@spettinichi 

But if I remove it I get the syntax error.

**Comment by TechBrain64** [comment]
Ok, I've made some progress:

![terraform_apply_screen#1](https://github.com/user-attachments/assets/c33e6ecc-519d-4bbb-b48b-1572874d6752)
![terraform_apply_screen#2](https://github.com/user-attachments/assets/749e20ec-57c2-46f7-8dc7-e7eb5baab1cf)

Seems the issue is in the Disk block. It actually created the VM and it's now waiting at the PXE menu.

**Comment by Tinyblargon** [comment]
@TechBrain64 Release 2.x is kinda busted in a lot of ways. It gets confused about which disk is which when you have more than one. The reason we are still on RC for 3.x is because, as we fixed the know issue, more fundamental issues with the provider kept creeping up.

**Comment by spettinichi** [comment]
okay weird thing, i was able to create a new VM using 3.0.01-rc3 and terraform 1.4.5 in my work environment.. besides the difference in terraform versions I’m unsure what is different. I had tried rc3 and rc6 at home with the same result. I hope to get some time to dig into the two soon

**Comment by spettinichi** [comment]
I still get this error when using Terraform 1.4.5, so that was not the issue. I copied my vm config to the work instance and was able to create the VM fine, so I dug in deeper and finally realized that at work I use the proxmox node hostname, but at home I use the IP. I have a variable set to use it for both the proxmox API path and the target_node, turns out target_node needs a hostname it doesn't understand the IP address. So once I separated the two it worked!

@TechBrain64 it looks like you're also using a variable for target_node, so make sure that is the hostname of your proxmox server and not the IP address

**Comment by TechBrain64** [comment]
@spettinichi 

Yes, I too was using IP address for target_node. I think once I made the change it was part of the reason why it finally ran. But, I also know the Disk block played a part. I'm right now working on starting from scratch and will use the latest RC code. After seeing what @Tinyblargon noted and reviewing the recent release documents, I will contribute what I can. I'm wanting to learn Terraform, Ansible and GitLab as I grow.

**Comment by TechBrain64** [comment]
@spettinichi 

I'll give an answer to that after I've confirmed original issue was in fact because of target_node.

**Comment by Tinyblargon** [comment]
I'll create some tickets for validating that the node has a valid name.

**Comment by TechBrain64** [comment]
@Tinyblargon, @spettinichi 

I have validated my script does in fact create a Proxmox VM when setting "target_node" to however it is displayed in console (name/IP); which make since given it's probably how API reference host/node.

Thanks for all you guys assistance.

**Comment by Tinyblargon** [comment]
The validation code mentioned by #1208 has been added.
