### ISSUE TITLE
Race condition when creating multiple machines

### ISSUE THREAD

**Issue by MatthaeusHarris** [Telmate/terraform-provider-proxmox#23]
When creating multiple machines in parallel, terraform will sometimes assign the same VMID to multiple machines.  Since it then tracks resources by the VMID, it will assume that two machines have successfully been provisioned when only one of them has.  Any further operation on either of those machines will be applied to the single VM.

**Comment by ggongaware** [comment]
This mutex here - https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/provider.go#L100
should avoid the scenario you're describing. Do you happen to run multiple terraform processes at the same time?

**Comment by MatthaeusHarris** [comment]
If I'm reading that code correctly, that code calls this function https://github.com/Telmate/proxmox-api-go/blob/master/proxmox/client.go#L362 which returns the next available ID but does not reserve it.  Subsequent calls to that function should return the same ID until a VM is provisioned to take that ID, yes?

I'm defining six machines (all identical, except for the name and terraform resource name) in a single main.tf file.

**Comment by ggongaware** [comment]
But it always calls it with the MaxID + 1, so it should always been one higher than the previous VM.
I do see the scenario - https://github.com/Telmate/proxmox-api-go/blob/master/proxmox/client.go#L374 that if you did hit an ID that was already in use, it would start over at zero. Could that be your scenario?

**Comment by MatthaeusHarris** [comment]
The VMID in question was 102.  I don't think that scenario works, but I may be misunderstanding something.

Here's the sequence of events I think is happening, simplified for just two VMS:
VM1: nextID = getNextID() + 1 // 102
VM2: nextID = getNextID() + 1 // also 102, since no VMs have been provisioned yet.
VM1: Provision with nextID
VM2: Provision with nextID

**Comment by ggongaware** [comment]
I've added a branch tp proxmox-api-go if you want to test: next_if_conflict

https://github.com/Telmate/proxmox-api-go/pull/12/files

Which would handle this sequence of events like this:
VM1: lastID = getNextID(0) // 102
VM2: lastID = getNextID(lastID + 1) tries 103, fails and returns getNextID(0)  // 102

The new flow should keep counting up until it finds an open one:
VM1: lastID = getNextID(0) // 102
VM2: lastID = getNextID(lastID + 1) tries 103, fails and returns getNextID(lastID + 1 + 1)  // 104

**Comment by mjdall** [comment]
In your config set your name to: 
```name            = "vm-name-${count.index}"```
in your main.tf file, the race condition is occuring because the vms have the same name and the code: 
```
dupVmr, _ := client.GetVmRefByName(vmName)

	forceCreate := d.Get("force_create").(bool)
	targetNode := d.Get("target_node").(string)

	if dupVmr != nil && forceCreate {
		pmParallelEnd(pconf)
		return fmt.Errorf("Duplicate VM name (%s) with vmId: %d. Set force_create=false to recycle", vmName, dupVmr.VmId())
	} else if dupVmr != nil && dupVmr.Node() != targetNode {
		pmParallelEnd(pconf)
		return fmt.Errorf("Duplicate VM name (%s) with vmId: %d on different target_node=%s", vmName, dupVmr.VmId(), dupVmr.Node())
	}

	vmr := dupVmr

	if vmr == nil {
		// get unique id
		nextid, err := nextVmId(pconf)
		if err != nil {
			pmParallelEnd(pconf)
			return err
		}
		vmr = pxapi.NewVmRef(nextid)

		vmr.SetNode(targetNode)
		// check if ISO or clone
		if d.Get("clone").(string) != "" {
			sourceVmr, err := client.GetVmRefByName(d.Get("clone").(string))
			if err != nil {
				pmParallelEnd(pconf)
				return err
			}
			log.Print("[DEBUG] cloning VM")
			err = config.CloneVm(sourceVmr, vmr, client)
			if err != nil {
				pmParallelEnd(pconf)
				return err
			}

			// give sometime to proxmox to catchup
			time.Sleep(5 * time.Second)

			err = prepareDiskSize(client, vmr, qemuDisks)
			if err != nil {
				pmParallelEnd(pconf)
				return err
			}

		} else if d.Get("iso").(string) != "" {
			config.QemuIso = d.Get("iso").(string)
			err := config.CreateVm(vmr, client)
			if err != nil {
				pmParallelEnd(pconf)
				return err
			}
		}
	} else {
		log.Printf("[DEBUG] recycling VM vmId: %d", vmr.VmId())

		client.StopVm(vmr)

		err := config.UpdateConfig(vmr, client)
		if err != nil {
			pmParallelEnd(pconf)
			return err
		}

		// give sometime to proxmox to catchup
		time.Sleep(5 * time.Second)

		err = prepareDiskSize(client, vmr, qemuDisks)
		if err != nil {
			pmParallelEnd(pconf)
			return err
		}
	}
	d.SetId(resourceId(targetNode, "qemu", vmr.VmId()))
```
is setting vmr := dupVmr, which then in turn will cause the code to go down the else statement. Also under your provider, the field `pm_parallel` can be set (defaults to 4) which will be the batch size of vms created at one time. I.e. clone 4, config, start, repeat until count is met. Setting name properly will solve this issue also.

**Comment by ggongaware** [comment]
I merged in next_if_conflict, closing unless some one sees the problem again

**Comment by XReyRobert-IBM** [comment]
It seems like this is still happening...
Using 2.9.6 I had to use  pm_parallel = 1 to avoid issues with vms sharing same ids messing states and spoiling deployments...
I'll try to get all logs to create a proper issue later.
