### ISSUE TITLE
When cloning a VM from template...newly created VM got "unused disk 0"

### ISSUE THREAD

**Issue by fguiet** [Telmate/terraform-provider-proxmox#239]
My configuration

Last master branch telmate/proxmox as of 08/11/2020

* Proxmox v 6.2-4

* Terraform v0.13.5
+ provider registry.example.com/telmate/proxmox v2.0.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

When I am cloning a VM template...newly created VM has got a unused disk...and system want to boot on it....

TIPS :

__Removing this part below from `resource_vm_qemu.go` (line 768) will solve this issue__

```go
err = config.UpdateConfig(vmr, client)
			if err != nil {
				// Set the id because when update config fail the vm is still created
				d.SetId(resourceId(targetNode, "qemu", vmr.VmId()))
				return err
			}
````

At the end go an error though...

```bash
[root@localhost proxmox]# terraform apply -auto-approve 2>&1 | tee tf.log
data.template_file.cloud_init_centos: Refreshing state... [id=9b006253e502423fad4c78fc14ce64c986c284d2ed37184bc23623e436aec5d0]
local_file.cloud_init_centos: Refreshing state... [id=b3896de95e63c8d2c16cf0b1e098110df91efb2a]
null_resource.cloud_init_centos: Refreshing state... [id=7868815670615807967]
proxmox_vm_qemu.vm-test-fred-01: Refreshing state... [id=pve/qemu/102]
proxmox_vm_qemu.vm-test-fred-01: Creating...
proxmox_vm_qemu.vm-test-fred-01: Still creating... [10s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [20s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [30s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [40s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [50s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [1m0s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [1m10s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [1m20s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [1m30s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [1m40s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [1m50s elapsed]

Error: network.0.firewall: '' expected type 'bool', got unconvertible type 'int'
```

![proxmox](https://user-images.githubusercontent.com/13849639/98469285-d67e7480-21de-11eb-83c4-2ee87430692e.JPG)

Terraform file I am using

```tf
# Create the VM
resource "proxmox_vm_qemu" "vm-test-fred-01" {
  ## Wait for the cloud-config file to exist

  depends_on = [
    null_resource.cloud_init_centos
  ]

  name            = "vm-test-fred-01"
  target_node     = "pve"

  # Clone from debian-cloudinit template
  clone = "CentOS7-Template"
  full_clone      = true
  #os_type = "cloud-init"
  #os_type = "linux"

  # Cloud init options
  cicustom = "user=local:snippets/cloud_init_centos.yml"

  memory       = 512
  agent        = 1

  # Set the boot disk paramters
  bootdisk = "scsi0"
  boot = "cdn"
  scsihw       = "virtio-scsi-single"

  disk {
    #id              = "0"
    size            = "10G"
    type            = "scsi"
    storage         = "local-lvm"        
    #storage_type    = "lvm-thin"
    #valid only with virtio disk or virtio-scsi-single controller
    #iothread        = true 
  }

  # Set the network
  network {
    #id = 0
    model = "virtio"
    bridge = "vmbr0"
  }

  # Cloud Init Settings
  ipconfig0 = "ip=dhcp"

  # Ignore changes to the network
  ## MAC address is generated on every apply, causing
  ## TF to think this needs to be rebuilt on every apply
  lifecycle {
     ignore_changes = [
       network
     ]
  }
}
```

**Comment by mleone87** [comment]
The updateconfig line messes up the vm because it does an incomplete POST for the storage part, tricking the proxmox api into creating a new disk of the indicated size, which also becomes the boot disk

I believe the problem is in the fact that the QemuDisks field is not updated after the clone and resize (which return the correct volume name)

**Comment by fguiet** [comment]
Hi  @mleone87 ,

Thank you...you made my day
Finally, got my VM created from a template!!

```bash
[root@localhost proxmox]# terraform apply -auto-approve 2>&1 | tee tf.log
data.template_file.cloud_init_centos: Refreshing state... [id=9b006253e502423fad4c78fc14ce64c986c284d2ed37184bc23623e436aec5d0]
local_file.cloud_init_centos: Refreshing state... [id=b3896de95e63c8d2c16cf0b1e098110df91efb2a]
null_resource.cloud_init_centos: Refreshing state... [id=7868815670615807967]
proxmox_vm_qemu.vm-test-fred-01: Refreshing state... [id=pve/qemu/102]
proxmox_vm_qemu.vm-test-fred-01: Creating...
proxmox_vm_qemu.vm-test-fred-01: Still creating... [10s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [20s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [30s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [40s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [50s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [1m0s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Creation complete after 1m6s [id=pve/qemu/102]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

This is a very ugly fix...but a Go programmer will make a PR

Typically I am just setting

config.QemuDisks[0]["file"] = qemuDisk["file"] 				
config.QemuDisks[0]["volume"] = qemuDisk["volume"]

from the config values of the clone VM I get from the API (`clonedConfig, err := pxapi.NewConfigQemuFromApi(vmr, client)`)

```go
// check if ISO or clone
		if d.Get("clone").(string) != "" {
			fullClone := 1
			if !d.Get("full_clone").(bool) {
				fullClone = 0
			}
			config.FullClone = &fullClone

			sourceVmr, err := client.GetVmRefByName(d.Get("clone").(string))
			if err != nil {
				return err
			}

			log.Print("[DEBUG] cloning VM")
			err = config.CloneVm(sourceVmr, vmr, client)

			if err != nil {
				return err
			}
			
			log.Print("[FRED] Fred was here")

			logger.Debug().Int("vmid", vmr.VmId()).Msgf("[FRED] Config : %+v", config)

			err = prepareDiskSize(client, vmr, qemuDisks)
			if err != nil {
				return err
			}

			clonedConfig, err := pxapi.NewConfigQemuFromApi(vmr, client)

			logger.Debug().Int("vmid", vmr.VmId()).Msgf("[FRED] clonedConfig 2 : %+v", clonedConfig)
			//clonedConfig.QemuDisks[0]["file"]
			//config.QemuDisks = clonedConfig.QemuDisks

			for _, qemuDisk := range clonedConfig.QemuDisks {
				config.QemuDisks[0]["file"] = qemuDisk["file"] 				
				config.QemuDisks[0]["volume"] = qemuDisk["volume"]
			}

			log.Print("[FRED] After I set stuff")
			logger.Debug().Int("vmid", vmr.VmId()).Msgf("[FRED] Config : %+v", config)

			err = config.UpdateConfig(vmr, client)
			if err != nil {
				// Set the id because when update config fail the vm is still created
				d.SetId(resourceId(targetNode, "qemu", vmr.VmId()))
				return err
			}

			log.Print("[DEBUG] RIEN")

			// give sometime to proxmox to catchup
			time.Sleep(time.Duration(d.Get("clone_wait").(int)) * time.Second)

			

		} else if d.Get("iso").(string) != "" {
			config.QemuIso = d.Get("iso").(string)
			err := config.CreateVm(vmr, client)
			if err != nil {
				return err
			}
		} else {
			return fmt.Errorf("Either clone or iso must be set")
		}
	}
```

**Comment by mleone87** [comment]
@fguiet 

I'm not a GO developer in any way but i think that your solution messes up if you have more than 1 disk

```
clonedConfig, err := pxapi.NewConfigQemuFromApi(vmr, client)
for _, qemuDisk := range clonedConfig.QemuDisks {
  config.QemuDisks[0]["file"] = qemuDisk["file"] 				
  config.QemuDisks[0]["volume"] = qemuDisk["volume"]
}
```

I think that simply(at the cost of one more GET) doing this should fix the update

```
config2, err := pxapi.NewConfigQemuFromApi(vmr, client)
config.QemuDisks = config2.QemuDisks
```

But I think that it's better to completely remove QemuDisks field from the config struct

**Comment by fguiet** [comment]
@mleone87 

I tell you this is an ugly fix....it is just to tell everyone the general idea of what's going wrong and how it can be fixed.

I let @doransmestad  to develop something better through a PR for instance.

Thank

**Comment by lesykm** [comment]
Just in case, this still reproduces in release 2.6.3 (so one which probably contains https://github.com/Telmate/terraform-provider-proxmox/commit/7226451210b7dd96eb956a5bbb46aba6fc11b103 )

**Comment by doransmestad** [comment]
Thanks for all the detail here!  I'm working on a fix.  My goal is to (1) detect this issue programmatically in the test cases (done!), and then (2) put in the fix to prevent it from happening (still to-do).   

I suspect @mleone87  is on to something when he suggests we're not currently updating our state appropriately after the clone completes - I want to dig a bit further though and see if/how this could affect other devices (e.g. network mac addresses updating).  It is also really odd that I'm not seeing this in my real infrastructure, but can reproduce it on my test proxmox host.  :thinking:   Maybe it depends on the storage type?  More digging to do..

On point (1) from above-  one issue is that the proxmox-api-go does not pass any information through about unused disks. I'm working on a branch that now does so.  I've also added it as a read-only field in terraform so I'll be able to write test cases to ensure no "extra" drives pop up post-clone to prevent future regressions.   While I agree with you @mleone87  that it would nice if disks were a separate resource, I'm hesitant to make that change with how tied a disk is to a virtual machine in proxmox itself (unlike EC2, Azure, VMWare, etc, managing disks as a first-class entity doesn't exist in proxmox as far as I'm aware).  I'll take a look at @Matchlighter's implementation for LXC disks though and see what can be done here in the future.

On point (2) - the actual fix for this, is still pending.  I'll let you know when I have something to test out!

**Comment by mleone87** [comment]
@doransmestad Thanks for you work! I can help you on develpment, no problem!

Let me insert the disk conf I set in the terraform file:
```
  disk {
    size            = "10G"
    type            = "virtio"
    storage         = "ssd500" #its a lvm-thin storage
  }
```

The upstream does:

1. CLONE
2. UPDATE
3. RESIZE

My actual "working" code does:

1. CLONE
2. RESIZE
3a. GET DISK CONF FROM API
3b. UPDATE

After CLONE we have a new VM, with a disk to resize and all the relevant fields to update.
After RESIZE we have a VM with the disk correctly resized but without the relevant fields to update.

But, without 3a:

- The QemuDisks struct is stil the one provided in the terraform file
- The Update function does not check if the actual state(**proxmox side!**) is different in any kind

The result is a POST with this parameter build up from the disk {} info we still have:
```
...
virtio0:10,ssd500
...
```
This confuses proxmox, we have a virtio0 disk but it's not the volume name we pass(we pass nothing), so, with some kind of logic from proxmox side, a new disk, virtio1:*newvolumename*:10G:ssd500 is created, is empty and it's the bootable one

We have to test if all kind of storages are affected in the same way


I think that we need to get the updates for disk and networkd devices every time we want to use updateConfig function from API

**Comment by AcidCrash1337** [comment]
I can confirm I am seeing the same issue as the OP (Proxmox 6.2-4, Terraform 0.13.5, Proxmox provider v2.6.4).  My storage type is "zfspool" in case that makes any difference.

I'd be happy to help test once a fix has been released.

**Comment by doransmestad** [comment]
Thanks @mleone87  that was helpful!    In the end I combined both your and @fguiet's recommendations together to create what I believe is a functional solution.  As @fguiet  discovered, it looks like we need to have both `file` and `volume` correctly set in the QemuDisks struct for the appropriate disk update to occur post-clone.  So I tweaked @fguiet's approach a bit to make it workable in situations where multiple disks were present.  Unfortunately just taking the whole QemuDisks from the clone's config doesn't work in situations where the clone has a single disk, but the user specifies 2 disks in the terraform config (1 from the clone, 1 to be created).

Still, it feels weird that we need to pull file and volume back from proxmox for this work correctly.. it's probably something that could be fixed directly in the proxmox-api-go library, but I'm not familiar enough with the inner workings to be sure.  Thus, I made a PR as described above that should fix this issue for now and perhaps in the future I'll look into doing something fancier in the api library.

Thanks again for the help, and if anyone tries out the code in the PR please let me know if you discover any issues.

**Comment by valentin2105** [comment]
Hello,
I just updated my provider to 2.6.4 but when I create a new VM (without the disk's ID), it move the clone disk to unused and create an useless empty disk. 
It work without defining any disk but I loose the Terraform value that expend my template disk size. 

Any plan to keep the ID in Disks and Networks ? or what is the new behavior to keep the template disk and expand it ? 

Thanks !

**Comment by doransmestad** [comment]
Hey @valentin2105  the issue of an empty disk appearing in 2.6.4 is resolved by the pull request above.  Once @ggongaware has an opportunity to take a look at the PR here and the one in the backing API library we use, you should be good to go.   

If you'd like it sooner you can compile the provider using the code from the pull request it's working for me so far!  Let me know if you go this path and have any issues.

**Comment by valentin2105** [comment]
@doransmestad  Thank a lot, I will wait the next release because my terraform steps are in CI Pipelines and I don't want to broke it. 

I just wondering a small thing, How Terraform will know how to deal with disks without IDs ? 
If my template have already 1 disk and I create a clone, with one disk defined in Terra, it should keep it, but If I defined two disk in Tera, how it will know which one is the first (the template one) ?

I don't know if I'm clear.

**Comment by doransmestad** [comment]
@valentin2105  to answer your question real quick-  the provider automatically sets the disk slot ("ID") based on the ordering of the blocks in your resource.   So you can manually specify the disk slot if you'd like, but if it is not present it will auto-compute it using a 0-based index.  For example:

```
disk {
   ....
}

disk {
   slot = 5
   ...
}
```

The first disk would be (for example) scsi0, and then the second would be scsi5.  If slot was not specified for that second disk, it would be slot 1 (scsi1).

**Comment by valentin2105** [comment]
Thanks @doransmestad , It's very cool.

**Comment by fguiet** [comment]
proxmox_vm_qemu.vm-test-fred-01: Creating...
proxmox_vm_qemu.vm-test-fred-01: Still creating... [10s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [20s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [30s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [40s elapsed]
Just tested out v2.6.5
Eveything's fine :)
Thumb up!

proxmox_vm_qemu.vm-test-fred-01: Still creating... [50s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [1m0s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Creation complete after 1m2s [id=pve/qemu/102]

**Comment by dabicata** [comment]
Hello, folks!
I still have this issue where unused disk is created and used as boot disk, i'm using version 2.5.6

**Comment by clayrisser** [comment]
I get this error when I choose a disk size of `10G`, but it does not happen when I choose a disk size of `20G`. Very strange and elusive bug.

```tf
resource "proxmox_vm_qemu" "vm" {
  disks {
    scsi {
      scsi0 {
        disk {
          storage  = "local-zfs"
          size     = "10G"
          iothread = true
        }
      }
    }
  }
}
```

**Comment by js94x** [comment]
@clayrisser Are you creating the new VM by cloning a template? 
I recognized a similar behaviour while cloning from a template.
If the hard disk of the desired vm was smaller than the hard disk of the template, I ran into the problem with unused disk 0.

**Comment by clayrisser** [comment]
Yes I am. That makes sense. Thanks.
